SETI-1829: test for reproducing zuul-cloner prune error
If zuul-cloner is aborted in the middle, it can leave the repository's
HEAD pointing to refs/remotes/origin/HEAD. If subsequent invocation of
zuul-cloner wants to work with the `git branch` command - eg. delete
stale remote tracking branches, git will fail with

    git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
      cmdline: git branch -d -r origin/extra_branch
      stderr: 'fatal: HEAD not found below refs/heads!'