Bump GitPython dependency
Main reason for this is that the old GitPython does not support newer
git version. My case was with git 2.16.1:

    Traceback (most recent call last):
      File "tests/test_cloner.py", line 677, in test_remote_head
        cloner.execute()
      File "zuul/lib/cloner.py", line 73, in execute
        self.prepareRepo(project, dest)
      File "zuul/lib/cloner.py", line 170, in prepareRepo
        repo.reset()
      File "zuul/merger/merger.py", line 94, in reset
        for ref in origin.refs:
      File "/home/hrubi/projects/zuul/.tox/py27/lib/python2.7/site-packages/git/remote.py", line 513, in refs
        out_refs.extend(RemoteReference.list_items(self.repo, remote=self.name))
      File "/home/hrubi/projects/zuul/.tox/py27/lib/python2.7/site-packages/git/util.py", line 745, in list_items
        out_list.extend(cls.iter_items(repo, *args, **kwargs))
      File "/home/hrubi/projects/zuul/.tox/py27/lib/python2.7/site-packages/git/refs/symbolic.py", line 594, in _iter_items
        for sha, rela_path in cls._iter_packed_refs(repo):
      File "/home/hrubi/projects/zuul/.tox/py27/lib/python2.7/site-packages/git/refs/symbolic.py", line 98, in _iter_packed_refs
        raise TypeError("PackingType of packed-Refs not understood: %r" % line)
    TypeError: PackingType of packed-Refs not understood: '# pack-refs with: peeled fully-peeled sorted'

GitPython was locked on <2.0.9 due to python2.6. We're already running on
python2.7, so bump it to the current version from PyPi.